/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.eni.clinique.ihm;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author plaurent2017
 */
public class ClientPanel extends javax.swing.JPanel {

    Session session;

    /**
     * Creates new form Client
     */
    public ClientPanel() {
        IconFontSwing.register(FontAwesome.getIconFont());
        initComponents();
        session = Session.getSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchPanel = new javax.swing.JPanel();
        RechercherBouton = new javax.swing.JButton();
        Ajout_SuppPanel = new javax.swing.JPanel();
        AjouterBouton = new javax.swing.JButton();
        SupprimerBouton = new javax.swing.JButton();
        Annuler_ValiderPanel = new javax.swing.JPanel();
        AnnulerBouton = new javax.swing.JButton();
        ValiderBouton = new javax.swing.JButton();
        ChampsPanel = new javax.swing.JPanel();
        VilleLabel = new javax.swing.JLabel();
        CodeTextField = new javax.swing.JTextField();
        AdresseTextField1 = new javax.swing.JTextField();
        NomTextField = new javax.swing.JTextField();
        CodeLabel = new javax.swing.JLabel();
        PrenomTextField = new javax.swing.JTextField();
        NomLabel = new javax.swing.JLabel();
        AdresseTextField = new javax.swing.JTextField();
        PrenomLabel = new javax.swing.JLabel();
        CodePostalTextField = new javax.swing.JTextField();
        AdresseLabel = new javax.swing.JLabel();
        VilleTextField = new javax.swing.JTextField();
        CodePostalLabel = new javax.swing.JLabel();
        Edit_Add_SupPanel = new javax.swing.JPanel();
        AjouterBoutonTable = new javax.swing.JButton();
        SupprimerBoutonTable = new javax.swing.JButton();
        EditerBoutonTable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AnimalTable = new javax.swing.JTable();

        setToolTipText("Client");
        setName("Client"); // NOI18N

        SearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        RechercherBouton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        RechercherBouton.setForeground(new java.awt.Color(0, 0, 0));
        RechercherBouton.setIcon(IconFontSwing.buildIcon(FontAwesome.SEARCH, 15));
        RechercherBouton.setText("Rechercher");
        RechercherBouton.setToolTipText("");
        RechercherBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RechercherBouton.setOpaque(false);
        RechercherBouton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RechercherBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherBoutonActionPerformed(evt);
            }
        });

        Ajout_SuppPanel.setLayout(new java.awt.GridLayout(1, 0));

        AjouterBouton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        AjouterBouton.setForeground(new java.awt.Color(0, 0, 0));
        AjouterBouton.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_SQUARE_O, 15));
        AjouterBouton.setText("Ajouter");
        AjouterBouton.setBorderPainted(false);
        AjouterBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AjouterBouton.setOpaque(true);
        AjouterBouton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Ajout_SuppPanel.add(AjouterBouton);

        SupprimerBouton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        SupprimerBouton.setForeground(new java.awt.Color(0, 0, 0));
        SupprimerBouton.setIcon(IconFontSwing.buildIcon(FontAwesome.MINUS_SQUARE_O, 20));
        SupprimerBouton.setText("Supprimer");
        SupprimerBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SupprimerBouton.setOpaque(false);
        SupprimerBouton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Ajout_SuppPanel.add(SupprimerBouton);

        Annuler_ValiderPanel.setLayout(new java.awt.GridLayout(1, 0));

        AnnulerBouton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        AnnulerBouton.setForeground(new java.awt.Color(0, 0, 0));
        AnnulerBouton.setIcon(IconFontSwing.buildIcon(FontAwesome.UNDO, 15));
        AnnulerBouton.setText("Annuler");
        AnnulerBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AnnulerBouton.setOpaque(false);
        AnnulerBouton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Annuler_ValiderPanel.add(AnnulerBouton);

        ValiderBouton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        ValiderBouton.setForeground(new java.awt.Color(0, 0, 0));
        ValiderBouton.setIcon(IconFontSwing.buildIcon(FontAwesome.CHECK, 15));
        ValiderBouton.setText("Valider");
        ValiderBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ValiderBouton.setOpaque(false);
        ValiderBouton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Annuler_ValiderPanel.add(ValiderBouton);

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RechercherBouton)
                .addGap(187, 187, 187)
                .addComponent(Ajout_SuppPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Annuler_ValiderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RechercherBouton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(Ajout_SuppPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Annuler_ValiderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        RechercherBouton.getAccessibleContext().setAccessibleName("RechercherBouton");

        VilleLabel.setText("Ville");
        VilleLabel.setToolTipText("");
        VilleLabel.setName("Ville"); // NOI18N

        CodeTextField.setName("CodeTextField"); // NOI18N

        AdresseTextField1.setName("AdresseTextField"); // NOI18N

        NomTextField.setName("NomTextField"); // NOI18N

        CodeLabel.setText("Code");
        CodeLabel.setToolTipText("Code");
        CodeLabel.setName("Code"); // NOI18N

        PrenomTextField.setName("PrenomTextField"); // NOI18N

        NomLabel.setText("Nom");
        NomLabel.setToolTipText("");
        NomLabel.setName("Nom"); // NOI18N

        AdresseTextField.setName("AdresseTextField"); // NOI18N

        PrenomLabel.setText("Prénom");
        PrenomLabel.setToolTipText("");
        PrenomLabel.setName("Prenom"); // NOI18N

        CodePostalTextField.setName("CodePostalTextField"); // NOI18N

        AdresseLabel.setText("Adresse");
        AdresseLabel.setToolTipText("");
        AdresseLabel.setName("Adresse"); // NOI18N

        VilleTextField.setName("VilleTextField"); // NOI18N

        CodePostalLabel.setText("CodePostal");
        CodePostalLabel.setToolTipText("");
        CodePostalLabel.setName("CodePostal"); // NOI18N

        javax.swing.GroupLayout ChampsPanelLayout = new javax.swing.GroupLayout(ChampsPanel);
        ChampsPanel.setLayout(ChampsPanelLayout);
        ChampsPanelLayout.setHorizontalGroup(
            ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChampsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChampsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AdresseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addComponent(CodeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addComponent(VilleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CodePostalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addComponent(CodePostalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(VilleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addComponent(AdresseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdresseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addComponent(PrenomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PrenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addComponent(NomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ChampsPanelLayout.setVerticalGroup(
            ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChampsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodeLabel))
                .addGap(18, 18, 18)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrenomLabel))
                .addGap(18, 18, 18)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdresseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdresseLabel))
                .addGap(18, 18, 18)
                .addComponent(AdresseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VilleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodePostalLabel))
                .addGap(15, 15, 15)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodePostalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VilleLabel))
                .addContainerGap())
        );

        Edit_Add_SupPanel.setLayout(new java.awt.GridLayout(1, 0));

        AjouterBoutonTable.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        AjouterBoutonTable.setForeground(new java.awt.Color(0, 0, 0));
        AjouterBoutonTable.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_SQUARE_O, 20));
        AjouterBoutonTable.setText("Ajouter");
        AjouterBoutonTable.setToolTipText("");
        AjouterBoutonTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AjouterBoutonTable.setOpaque(false);
        AjouterBoutonTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AjouterBoutonTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterBoutonTableActionPerformed(evt);
            }
        });
        Edit_Add_SupPanel.add(AjouterBoutonTable);

        SupprimerBoutonTable.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        SupprimerBoutonTable.setForeground(new java.awt.Color(0, 0, 0));
        SupprimerBoutonTable.setIcon(IconFontSwing.buildIcon(FontAwesome.MINUS_SQUARE_O, 20));
        SupprimerBoutonTable.setText("Supprimer");
        SupprimerBoutonTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SupprimerBoutonTable.setOpaque(false);
        SupprimerBoutonTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Edit_Add_SupPanel.add(SupprimerBoutonTable);

        EditerBoutonTable.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        EditerBoutonTable.setForeground(new java.awt.Color(0, 0, 0));
        EditerBoutonTable.setIcon(IconFontSwing.buildIcon(FontAwesome.FILE_TEXT_O, 20));
        EditerBoutonTable.setText("Editer");
        EditerBoutonTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditerBoutonTable.setOpaque(false);
        EditerBoutonTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Edit_Add_SupPanel.add(EditerBoutonTable);

        AnimalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(AnimalTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ChampsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Edit_Add_SupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addComponent(SearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChampsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Edit_Add_SupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterBoutonTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterBoutonTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjouterBoutonTableActionPerformed

    private void RechercherBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherBoutonActionPerformed
        try {
            // TODO add your handling code here:
            RechercheClientPopUp recherche = new RechercheClientPopUp(session.getFrameSession(), false);
            
            recherche.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ClientPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_RechercherBoutonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdresseLabel;
    private javax.swing.JTextField AdresseTextField;
    private javax.swing.JTextField AdresseTextField1;
    private javax.swing.JPanel Ajout_SuppPanel;
    private javax.swing.JButton AjouterBouton;
    private javax.swing.JButton AjouterBoutonTable;
    private javax.swing.JTable AnimalTable;
    private javax.swing.JButton AnnulerBouton;
    private javax.swing.JPanel Annuler_ValiderPanel;
    private javax.swing.JPanel ChampsPanel;
    private javax.swing.JLabel CodeLabel;
    private javax.swing.JLabel CodePostalLabel;
    private javax.swing.JTextField CodePostalTextField;
    private javax.swing.JTextField CodeTextField;
    private javax.swing.JPanel Edit_Add_SupPanel;
    private javax.swing.JButton EditerBoutonTable;
    private javax.swing.JLabel NomLabel;
    private javax.swing.JTextField NomTextField;
    private javax.swing.JLabel PrenomLabel;
    private javax.swing.JTextField PrenomTextField;
    private javax.swing.JButton RechercherBouton;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JButton SupprimerBouton;
    private javax.swing.JButton SupprimerBoutonTable;
    private javax.swing.JButton ValiderBouton;
    private javax.swing.JLabel VilleLabel;
    private javax.swing.JTextField VilleTextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
