/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.eni.clinique.ihm;

/**
 *
 * @author plaurent2017
 */
public class CliniqueVeterinaire extends javax.swing.JFrame {

    /**
     * Creates new form CliniqueVeterinaire
     */
    public CliniqueVeterinaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClinqueVeterinaire = new javax.swing.JMenuBar();
        Fichier = new javax.swing.JMenu();
        Deconnexion = new javax.swing.JMenuItem();
        Fermer = new javax.swing.JMenuItem();
        GestionRDV = new javax.swing.JMenu();
        PriseRDV = new javax.swing.JMenuItem();
        GestionClient = new javax.swing.JMenuItem();
        Agenda = new javax.swing.JMenu();
        GestionPersonnel = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinique Veterinaire");
        setName("CliniqueVeterinaire"); // NOI18N

        ClinqueVeterinaire.setToolTipText("");

        Fichier.setText("Fichier");

        Deconnexion.setText("Déconnexion");
        Deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnexionActionPerformed(evt);
            }
        });
        Fichier.add(Deconnexion);

        Fermer.setText("Fermer");
        Fichier.add(Fermer);

        ClinqueVeterinaire.add(Fichier);

        GestionRDV.setText("Gestion des rendez vous");

        PriseRDV.setText("Prise de rendez vous");
        GestionRDV.add(PriseRDV);

        GestionClient.setText("Gestion des clients");
        GestionRDV.add(GestionClient);

        ClinqueVeterinaire.add(GestionRDV);

        Agenda.setText("Agenda");
        ClinqueVeterinaire.add(Agenda);

        GestionPersonnel.setText("Gestion du personnel");
        ClinqueVeterinaire.add(GestionPersonnel);

        setJMenuBar(ClinqueVeterinaire);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnexionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeconnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CliniqueVeterinaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CliniqueVeterinaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CliniqueVeterinaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CliniqueVeterinaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CliniqueVeterinaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Agenda;
    private javax.swing.JMenuBar ClinqueVeterinaire;
    private javax.swing.JMenuItem Deconnexion;
    private javax.swing.JMenuItem Fermer;
    private javax.swing.JMenu Fichier;
    private javax.swing.JMenuItem GestionClient;
    private javax.swing.JMenu GestionPersonnel;
    private javax.swing.JMenu GestionRDV;
    private javax.swing.JMenuItem PriseRDV;
    // End of variables declaration//GEN-END:variables
}
