/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.eni.clinique.ihm;

import fr.eni.clinique.bo.Personnel;
import fr.eni.clinique.dao.EnumRole;
import fr.eni.clinique.dao.GetValuesDataBase;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author plaurent2017
 */
public class CliniqueVeterinaire extends javax.swing.JFrame {
    
    /**
     * Creates new form CliniqueVeterinaire
     */
    public CliniqueVeterinaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        ClinqueVeterinaire = new javax.swing.JMenuBar();
        Fichier = new javax.swing.JMenu();
        Deconnexion = new javax.swing.JMenuItem();
        Fermer = new javax.swing.JMenuItem();
        GestionRDV = new javax.swing.JMenu();
        PriseRDV = new javax.swing.JMenuItem();
        GestionClient = new javax.swing.JMenuItem();
        Agenda = new javax.swing.JMenu();
        GestionPersonnel = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinique Veterinaire");
        setName("CliniqueVeterinaire"); // NOI18N

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        ClinqueVeterinaire.setToolTipText("");

        Fichier.setText("Fichier");

        Deconnexion.setText("Déconnexion");
        Deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnexionActionPerformed(evt);
            }
        });
        Fichier.add(Deconnexion);

        Fermer.setText("Fermer");
        Fichier.add(Fermer);

        ClinqueVeterinaire.add(Fichier);

        GestionRDV.setText("Gestion des rendez vous");

        PriseRDV.setText("Prise de rendez vous");
        GestionRDV.add(PriseRDV);

        GestionClient.setText("Gestion des clients");
        GestionClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionClientActionPerformed(evt);
            }
        });
        GestionRDV.add(GestionClient);

        ClinqueVeterinaire.add(GestionRDV);

        Agenda.setText("Agenda");
        ClinqueVeterinaire.add(Agenda);

        GestionPersonnel.setText("Gestion du personnel");
        GestionPersonnel.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                GestionPersonnelMenuSelected(evt);
            }
        });
        GestionPersonnel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionPersonnelMouseClicked(evt);
            }
        });
        GestionPersonnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionPersonnelActionPerformed(evt);
            }
        });
        ClinqueVeterinaire.add(GestionPersonnel);

        setJMenuBar(ClinqueVeterinaire);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnexionActionPerformed
        this.dispose();
        ConnexionPageBuild connect = new ConnexionPageBuild();
        connect.initFrame();
    }//GEN-LAST:event_DeconnexionActionPerformed


    private void GestionPersonnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionPersonnelActionPerformed


    }//GEN-LAST:event_GestionPersonnelActionPerformed

    private void GestionPersonnelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionPersonnelMouseClicked
        // TODO add your handling code here:
        
        
          
    }//GEN-LAST:event_GestionPersonnelMouseClicked

    private void GestionPersonnelMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_GestionPersonnelMenuSelected
        
        PanelGeneral.setVisible(true);    
        this.setContentPane(new GestionPersonnel());
        PanelGeneral.repaint();
        PanelGeneral.revalidate();
    }//GEN-LAST:event_GestionPersonnelMenuSelected

    private void GestionClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GestionClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CliniqueVeterinaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CliniqueVeterinaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CliniqueVeterinaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CliniqueVeterinaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public void initFrame(String role) {
        AfficherEcranRole(role);
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        PanelGeneral.setVisible(false);
    }

    public void AfficherEcranRole(String role) {
        switch (role) {
            case EnumRole.ADM:
                break;
            case EnumRole.AST:
                Agenda.setVisible(false);
                GestionPersonnel.setVisible(false);
                break;
            case EnumRole.SEC:
                GestionPersonnel.setVisible(false);
                break;
            case EnumRole.VET:
                GestionPersonnel.setVisible(false);
                break;

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Agenda;
    private javax.swing.JMenuBar ClinqueVeterinaire;
    private javax.swing.JMenuItem Deconnexion;
    private javax.swing.JMenuItem Fermer;
    private javax.swing.JMenu Fichier;
    private javax.swing.JMenuItem GestionClient;
    private javax.swing.JMenu GestionPersonnel;
    private javax.swing.JMenu GestionRDV;
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JMenuItem PriseRDV;
    // End of variables declaration//GEN-END:variables
}
