/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.eni.clinique.ihm;

import fr.eni.clinique.bo.Client;
import fr.eni.clinique.dao.GetValuesDataBase;
import java.util.ArrayList;
import java.util.List;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author plaurent2017
 */
public class RechercheClientPopUp extends javax.swing.JDialog {

    private List<Client> listClient = new ArrayList<>();

    /**
     * Creates new form RechercheClientPopUp
     */
    public RechercheClientPopUp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopUpRechercheClient = new javax.swing.JPanel();
        TableResultRecherchePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultatRechercheTable = new javax.swing.JTable();
        RechercheClientPanel = new javax.swing.JPanel();
        RechercherClientBouton = new javax.swing.JButton();
        RechercheClientTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ResultatRechercheTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Code Postal", "Ville"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ResultatRechercheTable.setFocusable(false);
        ResultatRechercheTable.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(ResultatRechercheTable);

        javax.swing.GroupLayout TableResultRecherchePanelLayout = new javax.swing.GroupLayout(TableResultRecherchePanel);
        TableResultRecherchePanel.setLayout(TableResultRecherchePanelLayout);
        TableResultRecherchePanelLayout.setHorizontalGroup(
            TableResultRecherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TableResultRecherchePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addContainerGap())
        );
        TableResultRecherchePanelLayout.setVerticalGroup(
            TableResultRecherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableResultRecherchePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        RechercherClientBouton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        RechercherClientBouton.setForeground(new java.awt.Color(0, 0, 0));
        RechercherClientBouton.setIcon(IconFontSwing.buildIcon(FontAwesome.SEARCH,15));
        RechercherClientBouton.setText("Rechercher");
        RechercherClientBouton.setToolTipText("");
        RechercherClientBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RechercherClientBouton.setOpaque(false);
        RechercherClientBouton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RechercherClientBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherClientBoutonActionPerformed(evt);
            }
        });

        RechercheClientTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout RechercheClientPanelLayout = new javax.swing.GroupLayout(RechercheClientPanel);
        RechercheClientPanel.setLayout(RechercheClientPanelLayout);
        RechercheClientPanelLayout.setHorizontalGroup(
            RechercheClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RechercheClientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RechercheClientTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addComponent(RechercherClientBouton)
                .addContainerGap())
        );
        RechercheClientPanelLayout.setVerticalGroup(
            RechercheClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RechercheClientPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(RechercheClientTextField)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RechercheClientPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RechercherClientBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PopUpRechercheClientLayout = new javax.swing.GroupLayout(PopUpRechercheClient);
        PopUpRechercheClient.setLayout(PopUpRechercheClientLayout);
        PopUpRechercheClientLayout.setHorizontalGroup(
            PopUpRechercheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RechercheClientPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopUpRechercheClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TableResultRecherchePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PopUpRechercheClientLayout.setVerticalGroup(
            PopUpRechercheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpRechercheClientLayout.createSequentialGroup()
                .addComponent(RechercheClientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TableResultRecherchePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PopUpRechercheClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PopUpRechercheClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RechercherClientBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherClientBoutonActionPerformed
        // TODO add your handling code here:
        GetValuesDataBase getall = new GetValuesDataBase();
        listClient = getall.rechercheClient(RechercheClientTextField.getText());
        initFrame();
    }//GEN-LAST:event_RechercherClientBoutonActionPerformed

    public void initFrame() {
        int i = 0;
        for (Client cli : listClient) {
            if (!cli.isArchive()) {
                ResultatRechercheTable.setValueAt(cli.getNomClient(), i, 0);
                ResultatRechercheTable.setValueAt(cli.getPrenomClient(), i, 1);
                ResultatRechercheTable.setValueAt(cli.getCodePostal(), i, 2);
                ResultatRechercheTable.setValueAt(cli.getVille(), i, 3);
                i++;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PopUpRechercheClient;
    private javax.swing.JPanel RechercheClientPanel;
    private javax.swing.JTextField RechercheClientTextField;
    private javax.swing.JButton RechercherClientBouton;
    private javax.swing.JTable ResultatRechercheTable;
    private javax.swing.JPanel TableResultRecherchePanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
