/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.eni.clinique.ihm.GestionClient;

import fr.eni.clinique.ihm.Controller.ClientControler;
import fr.eni.clinique.ihm.IObservable;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author plaurent2017
 */
public class ClientPanel extends javax.swing.JPanel implements IObservable<IClientObserver> {

    private List<IClientObserver> observers = new ArrayList();

    /**
     * Creates new form Client
     */
    public ClientPanel() {
        IconFontSwing.register(FontAwesome.getIconFont());
        initComponents();
        this.registreObserver(ClientControler.getObserver());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchPanel = new javax.swing.JPanel();
        RechercherBouton = new javax.swing.JButton();
        Ajout_SuppPanel = new javax.swing.JPanel();
        AjouterBouton = new javax.swing.JButton();
        SupprimerBouton = new javax.swing.JButton();
        Annuler_ValiderPanel = new javax.swing.JPanel();
        ValiderBouton = new javax.swing.JButton();
        AnnulerBouton = new javax.swing.JButton();
        ChampsPanel = new javax.swing.JPanel();
        VilleLabel = new javax.swing.JLabel();
        CodeTextField = new javax.swing.JTextField();
        AdresseTextField1 = new javax.swing.JTextField();
        NomTextField = new javax.swing.JTextField();
        CodeLabel = new javax.swing.JLabel();
        PrenomTextField = new javax.swing.JTextField();
        NomLabel = new javax.swing.JLabel();
        AdresseTextField = new javax.swing.JTextField();
        PrenomLabel = new javax.swing.JLabel();
        CodePostalTextField = new javax.swing.JTextField();
        AdresseLabel = new javax.swing.JLabel();
        VilleTextField = new javax.swing.JTextField();
        CodePostalLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AnimalTable = new javax.swing.JTable();
        Edit_Add_SupPanel = new javax.swing.JPanel();
        AjouterBoutonTable = new javax.swing.JButton();
        SupprimerBoutonTable = new javax.swing.JButton();
        EditerBoutonTable = new javax.swing.JButton();

        setToolTipText("");
        setName("Client"); // NOI18N

        SearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        RechercherBouton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        RechercherBouton.setForeground(new java.awt.Color(0, 0, 0));
        RechercherBouton.setIcon(IconFontSwing.buildIcon(FontAwesome.SEARCH, 15));
        RechercherBouton.setText("Rechercher");
        RechercherBouton.setToolTipText("");
        RechercherBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RechercherBouton.setOpaque(false);
        RechercherBouton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RechercherBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherBoutonActionPerformed(evt);
            }
        });

        Ajout_SuppPanel.setLayout(new java.awt.GridLayout(1, 0));

        AjouterBouton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        AjouterBouton.setForeground(new java.awt.Color(0, 0, 0));
        AjouterBouton.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_SQUARE_O, 15));
        AjouterBouton.setText("Ajouter");
        AjouterBouton.setBorderPainted(false);
        AjouterBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AjouterBouton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AjouterBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterBoutonActionPerformed(evt);
            }
        });
        Ajout_SuppPanel.add(AjouterBouton);

        SupprimerBouton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        SupprimerBouton.setForeground(new java.awt.Color(0, 0, 0));
        SupprimerBouton.setIcon(IconFontSwing.buildIcon(FontAwesome.MINUS_SQUARE_O, 20));
        SupprimerBouton.setText("Supprimer");
        SupprimerBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SupprimerBouton.setOpaque(false);
        SupprimerBouton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SupprimerBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerBoutonActionPerformed(evt);
            }
        });
        Ajout_SuppPanel.add(SupprimerBouton);

        Annuler_ValiderPanel.setLayout(new java.awt.GridLayout(1, 0));

        ValiderBouton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        ValiderBouton.setForeground(new java.awt.Color(0, 0, 0));
        ValiderBouton.setIcon(IconFontSwing.buildIcon(FontAwesome.CHECK, 15));
        ValiderBouton.setText("Valider");
        ValiderBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ValiderBouton.setOpaque(false);
        ValiderBouton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ValiderBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderBoutonActionPerformed(evt);
            }
        });
        Annuler_ValiderPanel.add(ValiderBouton);

        AnnulerBouton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        AnnulerBouton.setForeground(new java.awt.Color(0, 0, 0));
        AnnulerBouton.setIcon(IconFontSwing.buildIcon(FontAwesome.UNDO, 15));
        AnnulerBouton.setText("Annuler");
        AnnulerBouton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AnnulerBouton.setOpaque(false);
        AnnulerBouton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AnnulerBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerBoutonActionPerformed(evt);
            }
        });
        Annuler_ValiderPanel.add(AnnulerBouton);

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RechercherBouton)
                .addGap(215, 215, 215)
                .addComponent(Ajout_SuppPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(Annuler_ValiderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RechercherBouton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(Ajout_SuppPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Annuler_ValiderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        RechercherBouton.getAccessibleContext().setAccessibleName("RechercherBouton");

        VilleLabel.setText("Ville");
        VilleLabel.setToolTipText("");
        VilleLabel.setName("Ville"); // NOI18N

        CodeTextField.setName("CodeTextField"); // NOI18N

        AdresseTextField1.setName("AdresseTextField"); // NOI18N

        NomTextField.setName("NomTextField"); // NOI18N

        CodeLabel.setText("Code");
        CodeLabel.setToolTipText("Code");
        CodeLabel.setName("Code"); // NOI18N

        PrenomTextField.setName("PrenomTextField"); // NOI18N

        NomLabel.setText("Nom");
        NomLabel.setToolTipText("");
        NomLabel.setName("Nom"); // NOI18N

        AdresseTextField.setName("AdresseTextField"); // NOI18N

        PrenomLabel.setText("Prénom");
        PrenomLabel.setToolTipText("");
        PrenomLabel.setName("Prenom"); // NOI18N

        CodePostalTextField.setName("CodePostalTextField"); // NOI18N

        AdresseLabel.setText("Adresse");
        AdresseLabel.setToolTipText("");
        AdresseLabel.setName("Adresse"); // NOI18N

        VilleTextField.setName("VilleTextField"); // NOI18N

        CodePostalLabel.setText("CodePostal");
        CodePostalLabel.setToolTipText("");
        CodePostalLabel.setName("CodePostal"); // NOI18N

        javax.swing.GroupLayout ChampsPanelLayout = new javax.swing.GroupLayout(ChampsPanel);
        ChampsPanel.setLayout(ChampsPanelLayout);
        ChampsPanelLayout.setHorizontalGroup(
            ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChampsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VilleLabel)
                            .addComponent(CodePostalLabel))
                        .addGap(55, 55, 55)
                        .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VilleTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CodePostalTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(AdresseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addComponent(CodeLabel)
                        .addGap(91, 91, 91)
                        .addComponent(CodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addComponent(AdresseLabel)
                        .addGap(72, 72, 72)
                        .addComponent(AdresseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addComponent(PrenomLabel)
                        .addGap(75, 75, 75)
                        .addComponent(PrenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChampsPanelLayout.createSequentialGroup()
                        .addComponent(NomLabel)
                        .addGap(94, 94, 94)
                        .addComponent(NomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ChampsPanelLayout.setVerticalGroup(
            ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChampsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodeLabel))
                .addGap(18, 18, 18)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrenomLabel))
                .addGap(18, 18, 18)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdresseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdresseLabel))
                .addGap(18, 18, 18)
                .addComponent(AdresseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VilleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodePostalLabel))
                .addGap(15, 15, 15)
                .addGroup(ChampsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodePostalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VilleLabel))
                .addContainerGap())
        );

        AnimalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Nom", "Sexe", "Couleur", "Race", "Espèce", "Tatouage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AnimalTable);

        Edit_Add_SupPanel.setLayout(new java.awt.GridLayout(1, 0));

        AjouterBoutonTable.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        AjouterBoutonTable.setForeground(new java.awt.Color(0, 0, 0));
        AjouterBoutonTable.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_SQUARE_O, 20));
        AjouterBoutonTable.setText("Ajouter");
        AjouterBoutonTable.setToolTipText("");
        AjouterBoutonTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AjouterBoutonTable.setOpaque(false);
        AjouterBoutonTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AjouterBoutonTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterBoutonTableActionPerformed(evt);
            }
        });
        Edit_Add_SupPanel.add(AjouterBoutonTable);

        SupprimerBoutonTable.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        SupprimerBoutonTable.setForeground(new java.awt.Color(0, 0, 0));
        SupprimerBoutonTable.setIcon(IconFontSwing.buildIcon(FontAwesome.MINUS_SQUARE_O, 20));
        SupprimerBoutonTable.setText("Supprimer");
        SupprimerBoutonTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SupprimerBoutonTable.setOpaque(false);
        SupprimerBoutonTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SupprimerBoutonTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerBoutonTableActionPerformed(evt);
            }
        });
        Edit_Add_SupPanel.add(SupprimerBoutonTable);

        EditerBoutonTable.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        EditerBoutonTable.setForeground(new java.awt.Color(0, 0, 0));
        EditerBoutonTable.setIcon(IconFontSwing.buildIcon(FontAwesome.FILE_TEXT_O, 20));
        EditerBoutonTable.setText("Editer");
        EditerBoutonTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditerBoutonTable.setOpaque(false);
        EditerBoutonTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditerBoutonTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditerBoutonTableActionPerformed(evt);
            }
        });
        Edit_Add_SupPanel.add(EditerBoutonTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Edit_Add_SupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Edit_Add_SupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ChampsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(SearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChampsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //Recherche client
    private void RechercherBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherBoutonActionPerformed
        for (IClientObserver obs : observers) {
            obs.AfficherRecherche();
        }
    }//GEN-LAST:event_RechercherBoutonActionPerformed
    //Ajout Animal
    private void AjouterBoutonTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterBoutonTableActionPerformed
        for (IClientObserver obs : observers) {
            obs.AjoutAnimal();
        }
    }//GEN-LAST:event_AjouterBoutonTableActionPerformed
    //Ajout Client
    private void AjouterBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterBoutonActionPerformed
        for (IClientObserver obs : observers) {
            obs.AjoutClient();
        }
    }//GEN-LAST:event_AjouterBoutonActionPerformed
    //Supprimer Client
    private void SupprimerBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerBoutonActionPerformed
        for (IClientObserver obs : observers) {
            obs.SupprimerClient();
        }
    }//GEN-LAST:event_SupprimerBoutonActionPerformed
    //Valider changement
    private void ValiderBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderBoutonActionPerformed
        for (IClientObserver obs : observers) {
            obs.ValiderChangement();
        }
    }//GEN-LAST:event_ValiderBoutonActionPerformed
    //Annuler Changement 
    private void AnnulerBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerBoutonActionPerformed
        for (IClientObserver obs : observers) {
            obs.AnnulerChangement();
        }
    }//GEN-LAST:event_AnnulerBoutonActionPerformed
    //Supprimer Animal
    private void SupprimerBoutonTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerBoutonTableActionPerformed
        for (IClientObserver obs : observers) {
            obs.ValiderChangement();
        }
    }//GEN-LAST:event_SupprimerBoutonTableActionPerformed
    //Editer Aniaml
    private void EditerBoutonTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditerBoutonTableActionPerformed
        for (IClientObserver obs : observers) {
            obs.EditerAnimal();
        }
    }//GEN-LAST:event_EditerBoutonTableActionPerformed

    public JTextField getAdresseTextField() {
        return AdresseTextField;
    }

    public void setAdresseTextField(JTextField AdresseTextField) {
        this.AdresseTextField = AdresseTextField;
    }

    public JTextField getAdresseTextField1() {
        return AdresseTextField1;
    }

    public void setAdresseTextField1(JTextField AdresseTextField1) {
        this.AdresseTextField1 = AdresseTextField1;
    }

    public JTextField getCodePostalTextField() {
        return CodePostalTextField;
    }

    public void setCodePostalTextField(JTextField CodePostalTextField) {
        this.CodePostalTextField = CodePostalTextField;
    }

    public JTextField getCodeTextField() {
        return CodeTextField;
    }

    public void setCodeTextField(JTextField CodeTextField) {
        this.CodeTextField = CodeTextField;
    }

    public JTextField getNomTextField() {
        return NomTextField;
    }

    public void setNomTextField(JTextField NomTextField) {
        this.NomTextField = NomTextField;
    }

    public JTextField getPrenomTextField() {
        return PrenomTextField;
    }

    public void setPrenomTextField(JTextField PrenomTextField) {
        this.PrenomTextField = PrenomTextField;
    }

    public JTextField getVilleTextField() {
        return VilleTextField;
    }

    public void setVilleTextField(JTextField VilleTextField) {
        this.VilleTextField = VilleTextField;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdresseLabel;
    private javax.swing.JTextField AdresseTextField;
    private javax.swing.JTextField AdresseTextField1;
    private javax.swing.JPanel Ajout_SuppPanel;
    private javax.swing.JButton AjouterBouton;
    private javax.swing.JButton AjouterBoutonTable;
    private javax.swing.JTable AnimalTable;
    private javax.swing.JButton AnnulerBouton;
    private javax.swing.JPanel Annuler_ValiderPanel;
    private javax.swing.JPanel ChampsPanel;
    private javax.swing.JLabel CodeLabel;
    private javax.swing.JLabel CodePostalLabel;
    private javax.swing.JTextField CodePostalTextField;
    private javax.swing.JTextField CodeTextField;
    private javax.swing.JPanel Edit_Add_SupPanel;
    private javax.swing.JButton EditerBoutonTable;
    private javax.swing.JLabel NomLabel;
    private javax.swing.JTextField NomTextField;
    private javax.swing.JLabel PrenomLabel;
    private javax.swing.JTextField PrenomTextField;
    private javax.swing.JButton RechercherBouton;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JButton SupprimerBouton;
    private javax.swing.JButton SupprimerBoutonTable;
    private javax.swing.JButton ValiderBouton;
    private javax.swing.JLabel VilleLabel;
    private javax.swing.JTextField VilleTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void registreObserver(IClientObserver observer) {
        this.observers.add(observer);
    }

    @Override
    public void unregistreObserver(IClientObserver observer) {
        this.observers.remove(observer);
    }
}
